<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	
	ga('create', '<?php echo $block->getTrackingCode(); ?>', '<?php echo $block->getTrackingName(); ?>');
	ga('send', 'pageview');

	ga('require', 'ecommerce', 'ecommerce.js');
	
	function makeTransaction(id){
		ga('ecommerce:clear');
		ga(	'ecommerce:addTransaction', {
			'id': id,            			// Transaction ID. Required.
			'affiliation': '<?php echo $block->getSeller(); ?>',  // Affiliation or store name.
			'revenue': 	'<?php echo $block->getData('product_price');?>',         // Grand Total.
			'shipping': '<?php echo $block->getData('product_shipping'); ?>',// Shipping.
			'tax': '<?php echo $block->getData('product_tax'); ?>'
			});
		ga(	'ecommerce:addItem', {
			'id': id,                     			// Transaction ID. Required.
		  	'name': '<?php echo $block->getData('product_name'); ?>',    			// Product name. Required.
		  	'sku': '<?php echo $block->getData('product_sku'); ?>',             	// SKU/code.
		  	'category': '<?php echo $block->getCategoryVariation(); ?>',	// Category or variation.
		  	'price': '<?php echo $block->getData('product_price'); ?>',                 	// Unit price.
		  	'quantity': '1'                		// Quantity.
			});
		
		ga('ecommerce:send');
	}
</script>