Analytics Loaded
<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	
	ga('create', '<?php echo $block->getAnalyticsTracking(); ?>', '<?php echo $block->getStoreURL(); ?>');
	ga('send', 'pageview');

	ga('require', 'ecommerce', 'ecommerce.js');
	
	function makeTransaction(id){
		ga('ecommerce:clear');
		ga(	'ecommerce:addTransaction', {
			'id': id,            			// Transaction ID. Required.
			'affiliation': 'AFFIALIAN',  // Affiliation or store name.
			'revenue': 	'89',         // Grand Total.
			'shipping': '39.5',// Shipping.
			'tax': '0'
			});
		ga(	'ecommerce:addItem', {
			'id': id,                     			// Transaction ID. Required.
		  	'name': 'AquaMin',    			// Product name. Required.
		  	'sku': 'PrentypeId: 47',             	// SKU/code.
		  	'category': 'CampCode: AL CampId: 45 EntryId: web SellerId: Emptiodirect',	// Category or variation.
		  	'price': '89',                 	// Unit price.
		  	'quantity': '1'                		// Quantity.
			});
		
		ga('ecommerce:send');
	}
</script>