<form 
    action="<?php echo $block->getFormAction() ?>" 
    method="post" 
    class="form-main"
    data-mage-init='{"validation":{}}'>

    <input type="hidden" name="merchant" value="<?php echo $block->getMerchant(); ?>" />
    <?php if (!$block->isMultiple()): ?>
        <input type="hidden" name="page" value="<?php echo $block->getPage(); ?>" />
    <?php endif; ?>
    <input type="hidden" name="campaignCode" value="<?php echo $block->getCampaignCode(); ?>" />
    <input type="hidden" name="seller" value="<?php echo $block->getSeller(); ?>" />
    <input type="hidden" name="country" value="<?php echo $block->getCountry(); ?>" />
    
    <div class="product-info">
        <h3 class="title"><?php echo $block->getData('title'); ?></h3>
        <?php if ($block->getData('short_desc') != ''): ?>
            <div class="desc"> - <?php echo $block->getData('short_desc'); ?></div>
        <?php endif; ?>
    </div>

    <?php if ($block->isMultiple()):?>
    <div class="control control-multiple">
        <?php 
            foreach($block->getPageMultiple() as $key => $control): 
                $checked = $key === 0 ? 'checked' : '';    
        ?>    
                <label>
                    <input name="page" type="radio" value="<?php echo $control[0] ?>" <?php echo $checked; ?>>
                    <?php echo htmlspecialchars_decode($control[1]); ?>
                </label>
        <?php endforeach ?>
    </div>
    <?php endif; ?>

    <div class="control control-input">
        <label><?php echo __('Phone');?> *</label>
        <input name="cellphone" 
            type="text" 
            placeholder="<?php echo __('Phone'); ?> *"
            value="<?php echo $block->getPostValue('cellphone'); ?>"
            data-validate='{"required":true}'
            >
    </div>

    <div class="control control-input">
        <label><?php echo __('Firstname');?> *</label>
        <input name="firstName" 
            type="text" 
            placeholder="<?php echo __('Firstname'); ?> *"
            value="<?php echo $block->getPostValue('firstName'); ?>"
            data-validate='{"required":true}'
            >
    </div>
    
    <div class="control control-input">
        <label><?php echo __('Lastname');?> *</label>
        <input name="lastName" 
            type="text" 
            placeholder="<?php echo __('Lastname'); ?> *"
            value="<?php echo $block->getPostValue('lastName'); ?>"
            data-validate='{"required":true}'
            >
    </div>

    <div class="control control-input">
        <label><?php echo __('Invoice Address');?> *</label>
        <input name="invoiceAddress" 
            type="text" 
            placeholder="<?php echo __('Invoice Address'); ?> *"
            value="<?php echo $block->getPostValue('invoiceAddress'); ?>"
            data-validate='{"required":true}'
            >
    </div>

    <div class="two-col-control">
        <div class="control control-input">
            <label><?php echo __('Postcode');?> *</label>
            <input name="invoiceZipcode" 
                type="text" 
                placeholder="<?php echo __('Postcode'); ?> *"
                value="<?php echo $block->getPostValue('invoiceZipcode'); ?>"
                data-validate='{"required":true}'
                >
        </div>

        <div class="control control-input">
            <label><?php echo __('Invoice City');?> *</label>
            <input name="invoiceCity" 
                type="text" 
                placeholder="<?php echo __('Invoice City'); ?> *"
                value="<?php echo $block->getPostValue('invoiceCity'); ?>"
                data-validate='{"required":true}'
                >
        </div>
    </div>

    <div class="control control-input">
        <label><?php echo __('Email');?> *</label>
        <input name="email" 
            type="text" 
            placeholder="<?php echo __('Email'); ?> *"
            value="<?php echo $block->getPostValue('email'); ?>"
            data-validate='{"email":true}'
            >
    </div>

    <div class="control gender control-radio">
        <label>
            <input name="gender" type="radio" value="1" checked="1">
            <?php echo __('Male');?>
        </label>
        <label>
            <input name="gender" type="radio" value="2">
            <?php echo __('Female');?>
        </label>
    </div>

    <div class="payment-method">
        <p><strong><?php echo __('Payment Method');?></strong></p>

        <div class="control payment-methods control-radio">
            <label>
                <input name="paymentMethod" type="radio" value="<?php echo __('Invoice'); ?>" checked="1">
                <?php echo __('Invoice');?>
            </label>
            <label>
                <input name="paymentMethod" type="radio" value="VISA">
                <img src="<?php echo $block->getViewFileUrl('Prymag_PurchaseForm::images/visa.png'); ?>" />
            </label>
            <label>
                <input name="paymentMethod" type="radio" value="MC">
                <img src="<?php echo $block->getViewFileUrl('Prymag_PurchaseForm::images/mastercard.png'); ?>" />
            </label>
            <label>
                <input name="paymentMethod" type="radio" value="PayPal Classic">
                <img src="<?php echo $block->getViewFileUrl('Prymag_PurchaseForm::images/paypal.jpg'); ?>" />
            </label>
        </div>
    </div>

    <div class="control consent control-checkbox">
        <label>
            <input 
                name="integrity.EMAIL_INFO" 
                type="checkbox" 
                
                data-validate='{"required":true}'
                />
            <?php echo __('Subscribe to Newsletter');?>
        </label>
        <label>
            <input 
                name="GDPR_1" 
                type="checkbox" 
                
                data-validate='{"required":true}'
                />
            <?php 
                $terms = '<a href="#" class="toggle-terms-modal">' . __('Terms') . '</a>';
                $privacyPolicy = '<a href="#" class="toggle-policy-modal">' . __('Privacy Policy') . '</a>';
            ?>
            <?php echo __("I agree to the %1 and have read the %2", $terms, $privacyPolicy);?>
            <div style="display:none;">
                <?php echo $block->makeModal($block->getTermsBlockId(), '.toggle-terms-modal'); ?>
                <?php echo $block->makeModal($block->getPolicyBlockId(), '.toggle-policy-modal'); ?>
            </div>
        </label>
    </div>

    <?php echo $block->getMobileButton(); ?>

    <button type="submit" class="action submit primary">
        <span><?php echo __('Buy Now!'); ?></span>
    </button>

    <div class="conditions-text">
        <?php echo htmlspecialchars_decode($block->getData('conditions_text'));?>
    </div>

    <?php 
        $dataPersistor = $block->getDataPersistor();
        $dataPersistor->clear('purchase_form_analytics');
        $dataPersistor->set('purchase_form_analytics', $block->getData());
    ?>
</form>

