<div class="sms-button hidden">
    <button type="button" 
        data-sms_number="<?php echo $block->getSMSNumber();?>" 
        data-sms_body="<?php echo $block->getData('sms_body'); ?>"
        class="action send-sms">
        <span class="action-name">
            <i class="fa fa-mobile"></i>
            <?php echo __('Order via SMS'); ?>
        </span>
        <span class="action-info"><?php echo __("Print <strong>%1</strong>", $block->getData('sms_body')); ?></span>
    </button>
</div>

<script type="text/x-magento-init">
        {
            "*": {
                "Prymag_PurchaseForm/js/sms-button": {
                    
                }
            }
        }
</script>