<div class="sms-button hidden">
    <button type="button" 
        data-sms_number="<?php echo $block->getSMSNumber();?>" 
        data-sms_body="<?php echo $block->getData('sms_body'); ?>"
        class="action send-sms">
        <i class="fa fa-mobile"></i>
        <?php echo __('Order via SMS'); ?>
    </button>
</div>

<script type="text/x-magento-init">
        {
            "*": {
                "Prymag_PurchaseForm/js/sms-button": {
                    
                }
            }
        }
</script>